package eu.arrowhead.dto.enums;

public enum ServiceInterfacePolicy {
	NONE, CERT_AUTH, TIME_LIMITED_TOKEN_AUTH, USAGE_LIMITED_TOKEN_AUTH, RSASHA256_AES256GCM_JSON_WEB_TOKEN_AUTH, RSASHA256_AES128GCM_JSON_WEB_TOKEN_AUTH;
}